### PR TITLE
pnpm install with fresh pnpm and node-addon-api

### PR DESCRIPTION
**Pull request by andriytyurnikov**
On MacOS (Sequoia)
```
pnpm install
```
Fails due to lack of missing `node-addon-api` dependency.

### CODE REVIEW

**Comment by bpierre** [comment]
Could you please try again with pnpm 8? We haven’t moved to 9 yet because of CI issues. Thanks!

**Comment by andriytyurnikov** [comment]
@bpierre , I did tried, yet it produced another errors around same package - `sharp`

This image generation thing is using C++ extension, and it seems quite brittle.

To make things more scary it looks like node-gyp has some python requirements.

**Comment by bpierre** [comment]
@andriytyurnikov could you please paste the output when running `pnpm install`?

**Comment by andriytyurnikov** [comment]
> I wonder if this is a platform-specific thing, I don’t have these dependencies (Linux) 🤔
> 
I mean... brittleness of FFI packages is pretty much always platform specific - sometimes it is a compiler flag, native library presence or version, etc. It stops working on some platform, and then people either fix it, or remove it, or they give up and introduce Docker...

Here is my output of npm install:
```
node_modules/.pnpm/sharp@0.33.5/node_modules/sharp: Running install script, failed in 4.8s
.../sharp@0.33.5/node_modules/sharp install$ node install/check
│ sharp: Detected globally-installed libvips v8.16.0
│ sharp: Attempting to build from source via node-gyp
│ sharp: Found node-addon-api 
│ sharp: Found node-gyp 10.0.1
│ sharp: See https://sharp.pixelplumbing.com/install#building-from-source
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@22.11.0 | darwin | arm64
│ gyp info chdir src
│ (node:94591) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.…
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ gyp info find Python using Python version 3.12.7 found at "/Users/andriytyurnikov/.asdf/installs/py…
│ gyp info spawn /Users/andriytyurnikov/.asdf/installs/python/3.12.7/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/andriytyurnikov/.asdf/installs/nodejs/22.11.0/lib/node_modules/pnpm/d…
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/andriytyurnikov/Code/dgndao/bold/node_modules/.pnpm/sharp@0.33.5/node…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/andriytyurnikov/.asdf/installs/nodejs/22.11.0/lib/node_modules/pnpm/d…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/andriytyurnikov/Library/Caches/node-gyp/22.11.0/include/node/common.g…
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/andriytyurnikov/Library/Caches/node-gyp/22.11.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/andriytyurnikov/.asdf/installs/nodejs/22.11.0/lib/node…
│ gyp info spawn args   '-Dnode_lib_file=/Users/andriytyurnikov/Library/Caches/node-gyp/22.11.0/<(tar…
│ gyp info spawn args   '-Dmodule_root_dir=/Users/andriytyurnikov/Code/dgndao/bold/node_modules/.pnpm…
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ <string>:114: SyntaxWarning: invalid escape sequence '\/'
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│   CC(target) Release/obj.target/nothing/../../../../node-addon-api@2.0.2/node_modules/node-addon-ap…
│   LIBTOOL-STATIC Release/nothing.a
│ warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lib…
│   TOUCH Release/obj.target/libvips-cpp.stamp
│   CXX(target) Release/obj.target/sharp-darwin-arm64/common.o
│ ../common.cc:12:10: fatal error: 'napi.h' file not found
│    12 | #include <napi.h>
│       |          ^~~~~~~~
│ 1 error generated.
│ make: *** [Release/obj.target/sharp-darwin-arm64/common.o] Error 1
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/Users/andriytyurnikov/.asdf/installs/nodejs/22.11.0/lib…
│ gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
│ gyp ERR! System Darwin 24.0.0
│ gyp ERR! command "/Users/andriytyurnikov/.asdf/installs/nodejs/22.11.0/bin/node" "/Users/andriytyur…
│ gyp ERR! cwd /Users/andriytyurnikov/Code/dgndao/bold/node_modules/.pnpm/sharp@0.33.5/node_modules/s…
│ gyp ERR! node -v v22.11.0
│ gyp ERR! node-gyp -v v9.4.1
│ gyp ERR! not ok 
└─ Failed in 4.8s at /Users/andriytyurnikov/Code/dgndao/bold/node_modules/.pnpm/sharp@0.33.5/node_modules/sharp
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by bpierre** [comment]
Yes I was trying to understand why it was building from source with your environment and not mine, it might be caused by [the presence of libvips](https://sharp.pixelplumbing.com/install#building-from-source).

Could you try this?

```sh
SHARP_IGNORE_GLOBAL_LIBVIPS=1 pnpm install
```

**Comment by andriytyurnikov** [comment]
@bpierre , BINGO. You've nailed it. Thanks.
I am closing a PR though, as I've polluted it enough already.

What do you think should be done?

**Pull request closed without merging**
